language: ruby
cache: bundler
rvm:
  - ruby-head
  - 2.6.2
  - 2.5.5
  - 2.4.5
  - 2.3.8
gemfile:
  - gemfiles/rails_6.0.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_4.2.gemfile
matrix:
  exclude:
    - rvm: 2.4.5
      gemfile: gemfiles/rails_6.0.gemfile
    - rvm: 2.3.8
      gemfile: gemfiles/rails_6.0.gemfile
  allow_failures:
    - rvm: ruby-head
