language: ruby
cache: bundler
rvm:
  - ruby-head
  - 2.7.3
  - 2.6.6
  - 2.5.8
gemfile:
  - gemfiles/rails_6.1.gemfile
  - gemfiles/rails_6.0.gemfile
  - gemfiles/rails_5.2.gemfile
matrix:
  allow_failures:
    - rvm: ruby-head
