name: CI

on: [push, pull_request]

jobs:
  test:
    name: CI
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.0", "3.1", "3.2", "3.3"]
        gemfile: [rails_6.1, rails_7.0, rails_7.1]
        include:
          - ruby: "2.7"
            gemfile: rails_5.2
          - ruby: "3.0"
            gemfile: rails_6.0
          - ruby: head
            gemfile: rails_7.1
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rspec
        continue-on-error: ${{ endsWith(matrix.ruby, 'head') }}
