name: CI

on: [push, pull_request]

jobs:
  test:
    name: CI
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.5, 2.6, 2.7, 3.0, head]
        gemfile: ["rails_5.2", "rails_6.0", "rails_6.1", "rails_head"]
        experimental: [false]
        exclude:
          - ruby: 3.0
            gemfile: rails_5.2
          - ruby: head
            gemfile: rails_5.2
          - ruby: 2.5
            gemfile: rails_head
          - ruby: 2.6
            gemfile: rails_head
          - ruby: 2.7
            gemfile: rails_head
            experimental: false
          - ruby: 3.0
            gemfile: rails_head
            experimental: false
          - ruby: head
            gemfile: rails_6.0
          - ruby: head
            gemfile: rails_6.1
          - ruby: head
            gemfile: rails_head
            experimental: false
        include:
          - ruby: 2.7
            gemfile: rails_head
            experimental: true
          - ruby: 3.0
            gemfile: rails_head
            experimental: true
          - ruby: head
            gemfile: rails_head
            experimental: true
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rspec
